[project]
name = "cycling-website"
version = "1.0.0"
description = "Cycling routes website with GPX management"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
python = "==3.11"
fastapi = "*"
uvicorn = "*"
elasticsearch = "==8.11.0"
aiohttp = "*"
gpxpy = "*"
boto3 = "*"
python-multipart = "*"
python-jose = "*"
passlib = "*"
python-dotenv = "*"
requests = "*"
ruff = "*" # Python linter and formatter
pre-commit = "*" # Git hooks framework
pytest = "*"
pytest-cov = "*"

[tasks]
start-backend = { cmd = "uvicorn main:app --reload --host 0.0.0.0 --port 8000", cwd = "backend" }
start-frontend = { cmd = "npm run dev", cwd = "frontend", depends-on = ["frontend-install"] }
frontend-install = { cmd = "npm install", cwd = "frontend" }
frontend-build = { cmd = "npm run build", cwd = "frontend", depends-on = ["frontend-install"] }
setup-elasticsearch = { cmd = "python scripts/setup_elasticsearch.py" }
lint-all = { depends-on = ["lint-backend", "lint-frontend"] }
format-all = { depends-on = ["format-backend", "format-frontend"] }
type-check = { depends-on = ["type-check-frontend"] }
type-check-frontend = { cmd = "npm run type-check", cwd = "frontend" }
install-pre-commit = { cmd = "pre-commit install" }
pre-commit = { cmd = "pre-commit run --all-files" }
pre-commit-update = { cmd = "pre-commit autoupdate" }
lint-backend = { cmd = "ruff check backend/ scripts/ --fix" }
lint-frontend = { cmd = "npm run lint", cwd = "frontend" }
format-backend = { cmd = "ruff format backend/ scripts/" }
format-frontend = { cmd = "npm run format", cwd = "frontend" }
test-backend = { cmd = "pytest -q --cov=backend --cov-report=term-missing" }
test-frontend = { cmd = "npm install --no-audit --no-fund && npm run test:cov", cwd = "frontend" }
