[project]
name = "cycling-website"
version = "1.0.0"
description = "Cycling routes website with GPX management"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
python = "==3.11"
fastapi = "*"
uvicorn = "*"
elasticsearch = "==8.11.0"
aiohttp = "*"
gpxpy = "*"
boto3 = "*"
python-multipart = "*"
python-jose = "*"
passlib = "*"
python-dotenv = "*"
requests = "*"
ruff = "*" # Python linter and formatter
black = "*" # Python code formatter
isort = "*" # Import sorter
pre-commit = "*" # Git hooks framework

[tasks]
[tasks.start-backend]
cmd = "cd backend && uvicorn main:app --reload --host 0.0.0.0 --port 8000"

[tasks.start-frontend]
cmd = "cd frontend && npm run dev"

[tasks.setup-elasticsearch]
cmd = "python scripts/setup_elasticsearch.py"

[tasks.lint-python]
cmd = "ruff check backend/ scripts/ --fix"

[tasks.format-python]
cmd = "ruff format backend/ scripts/"

[tasks.lint-all]
cmd = "ruff check backend/ scripts/ --fix && cd frontend && npm run lint"

[tasks.format-all]
cmd = "ruff format backend/ scripts/ && cd frontend && npm run format"

[tasks.install-pre-commit]
cmd = "pre-commit install"

[tasks.pre-commit]
cmd = "pre-commit run --all-files"

[tasks.pre-commit-hooks]
cmd = "pre-commit run --all-files --hook-stage pre-commit"

[tasks.pre-commit-update]
cmd = "pre-commit autoupdate"
