[project]
name = "cycling-website"
version = "1.0.0"
description = "Cycling routes website with GPX management"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
python = "==3.11"
fastapi = "*"
uvicorn = "*"
elasticsearch = "==8.11.0"
aiohttp = "*"
gpxpy = "*"
boto3 = "*"
python-multipart = "*"
python-jose = "*"
passlib = "*"
python-dotenv = "*"
requests = "*"
ruff = "*" # Python linter and formatter
pre-commit = "*" # Git hooks framework
pytest = "*"
pytest-cov = "*"

[tasks]
[tasks.start-backend]
cmd = "cd backend && uvicorn main:app --reload --host 0.0.0.0 --port 8000"

[tasks.start-frontend]
cmd = "cd frontend && npm run dev"
depends-on = ["frontend-install"]

[tasks.frontend-install]
cmd = "cd frontend && npm install"

[tasks.frontend-build]
cmd = "cd frontend && npm run build"
depends-on = ["frontend-install"]

[tasks.setup-elasticsearch]
cmd = "python scripts/setup_elasticsearch.py"

[tasks.lint-all]
cmd = "ruff check backend/ scripts/ --fix && cd frontend && npm run lint"

[tasks.format-all]
cmd = "ruff format backend/ scripts/ && cd frontend && npm run format"

[tasks.type-check]
cmd = "cd frontend && npm run type-check"

[tasks.install-pre-commit]
cmd = "pre-commit install"

[tasks.pre-commit]
cmd = "pre-commit run --all-files"

[tasks.pre-commit-update]
cmd = "pre-commit autoupdate"

[tasks.test]
cmd = "pytest -q --cov=backend --cov-report=term-missing"
