name: Backend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          activate-environment: true
          locked: true

      - name: Show pixi version
        run: pixi --version

      - name: Create environment file
        run: cp .env/.env.local.example .env/local

      - name: Run backend tests with coverage
        run: pixi run -e dev -- test-backend

      - name: Upload coverage summary
        if: always()
        run: |
          echo "Coverage summary:" >> $GITHUB_STEP_SUMMARY
          pixi run -e dev -- test-backend | sed -n '/^=============================== tests coverage/,/^[0-9].*passed/p' >> $GITHUB_STEP_SUMMARY
