name: Frontend Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          activate-environment: true
          locked: true

      - name: Show pixi version
        run: pixi --version

      - name: Run lint
        run: pixi run -e dev lint-frontend

      - name: Run frontend unit tests with coverage
        run: pixi run -e dev -- test-frontend

      - name: Upload coverage summary
        if: always()
        run: |
          echo "Frontend Coverage summary:" >> $GITHUB_STEP_SUMMARY
          cd frontend && npx vitest --coverage --reporter=default || true
